server:
  port: 8084

spring:
  application:
    name: register-service
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka